# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: BSD-2-Clause

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/android-qt6.yml
      - /gitlab-templates/craft-android-qt6-apks.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml
